EventStarter/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'EventStarter.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^basic/', include('basic.urls', namespace='basic')),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
)

basic/urls.py
from django.conf.urls import patterns, url
from models import UserProfile, Event, Guest
from django.views import generic
from basic import views

all_user = {
    'queryset': UserProfile.objects.all()
}

all_event = {
    'queryset': Event.objects.all()
}


all_guest = {
    'queryset': Guest.objects.all()
}

urlpatterns = patterns(
    '',
    url(r'^$', generic.TemplateView.as_view(template_name='basic/index.html'),
        name='index'),
    url(r'^events/$', generic.ListView.as_view(model=Event),
        name='list_events'),
    url(r'^events/(?P<pk>\d+)$', generic.DetailView.as_view(model=Event),
        name='detail_event'),
    url(r'^new/$', views.SignUpView.as_view(),
        name='user_new'),
)

basic/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):

    user = models.OneToOneField(User)
    date_birth = models.DateField()

    def __unicode__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)

    class Meta:
        verbose_name_plural = 'Users Profile'


class Event(models.Model):

    name = models.CharField(max_length=120)
    description = models.TextField()
    image = models.ImageField(upload_to='event_images', null=True, blank=True)
    private = models.BooleanField()
    start_time = models.DateTimeField()
    location = models.CharField(max_length=200)
    full_amount = models.DecimalField(max_digits=11, decimal_places=2)
    amount_donated = models.DecimalField(max_digits=11,
                                         decimal_places=2, default=0.0)
    user_profile = models.ForeignKey(UserProfile)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Events'


class Guest(models.Model):

    name = models.CharField(max_length=80)
    email = models.EmailField(unique=True)
    cod_invited = models.CharField(max_length=50, editable=False, null=True)
    expired = models.DateTimeField(editable=False, blank=True)
    event = models.ForeignKey(Event)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.cod_invited = '{}{}'.format(self.name, self.id)
        self.expired = self.event.start_time
        super(Guest, self).save(*args, **kwargs)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Guests'

basic/forms.py
from django import forms
from basic.models import UserProfile
from django.contrib.auth.models import User


class UserProfileForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField(widget=forms.EmailInput())
    password = forms.CharField(widget=forms.PasswordInput())
    date_birth = forms.DateField(input_formats=['%d/%m/%Y'])

    def save(self):
        data = self.cleaned_data
        u = User.objects.create_user(username=data['username'],
                                     password=data['password'],
                                     email=data['email'],
                                     first_name=data['first_name'],
                                     last_name=data['last_name'])

        UserProfile.objects.get_or_create(user=u,
                                          date_birth=data['date_birth'])

basic/views.py
# -*- coding: utf-8 -*-
from basic.forms import UserProfileForm
from django.views.generic import FormView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class LoggedInMixin(object):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoggedInMixin, self).dispatch(*args, **kwargs)


class SignUpView(SuccessMessageMixin, FormView):
    form_class = UserProfileForm
    template_name = 'basic/userprofile_form.html'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            form.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        return self.render_to_response(self.get_context_data(registered=True))

templates/basic/base.html
<html lang="pt-br">
	<head>
		<title>EventStarter</title>
		<link rel="stylesheet"  type="text/css" href="" />
	</head>
	<body>
		<header>
			<nav>
				<a href="{% url 'basic:index' %}">{% block title %} EventStarter {% endblock %}</a>  |

				{% if user.is_anonymous %}
				<a href="{% url 'basic:user_new' %}">Sign Up</a> |
				<a href="{% url 'django.contrib.auth.views.login' %}">Log In</a>
				{% else %}
				{{ user }} |
				<a href="#">Meus Eventos</a>
				<a href="{% url 'django.contrib.auth.views.logout' %}">Logout</a>
				{% endif %}
			</nav>
		</header>
		{% if registered %}
			<ul class="messages">
				<li class="success">
					<p>Usuário cadastrado com sucesso!</p>
					<p>Um email foi enviado para sua caixa postal.</p>
				</li>
			</ul>
		{% endif %}
		{% block content %}{% endblock %}
	</body>
</html>

templates/basic/event_detail.html
{% extends "basic/base.html" %}
{% block content %}
	<h1> {{ object.name }}</h1>

	<p>Dono do evento: {{ object.user_profile }}</p>
	<p>Descrição: {{ object.description }} </p>
	<p>Data Início: {{ object.start_time }}</p>
	<p>Local: {{ object.location }}</p>
	<p>Orçamento: {{ object.full_amount }}</p>
	<p>Doação: {{ object.amount_donated }}</p>
	<p>Convidados:
		<ul>
		{% for guest in object.guest_set.all %}
			<li> {{ guest }} </li>	
		{% endfor %}
		</ul>
	</p>
{% endblock %}

templates/basic/event_list.html
{% extends "basic/base.html" %}
{% block content %}

	<h1>Lista de Eventos</h1>
	<ul>
	{% for event in object_list %}
	<li><a href="{% url 'basic:detail_event' event.id %}">{{ event }}</a></li>	
	{% endfor %}
	</ul>
{% endblock %}

templates/basic/index.html
{% extends "basic/base.html" %}
{% block content %}
		<main>
			<h1>Seu evento começa aqui</h1>
			<p><a>Crie um evento</a> ou <a href="{% url 'basic:list_events' %}">explore os eventos que queira ir.</a></p>
		</main>
{% endblock %}

templates/basic/userprofile_form.html
{% extends 'basic/base.html' %}
{% block content %}
{% if form %}
	<h1>Sign Up</h1>
	<form method="post" action="{% url 'basic:user_new' %}">
	{% csrf_token %}
	{{ form.as_p }}
	<input id="save_user" type="submit" value="Save" />
	</form>
{% endif %}
{% endblock %}